[package]
name = "rust-chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rand = "0.3.15"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx"]